# Generated by Django 5.2.4 on 2025-08-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_department_customuser_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_paper', models.CharField(max_length=255)),
                ('author_position', models.CharField(choices=[('first', 'First Author'), ('second', 'Second Author'), ('third', 'Third Author'), ('fourth', 'Fourth Author'), ('fifth', 'Fifth Author'), ('sixth', 'Sixth Author'), ('corresponding', 'Corresponding Author'), ('other', 'Other Author')], default='first', max_length=20)),
                ('corresponding_author', models.CharField(blank=True, max_length=100, null=True)),
                ('journal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('ISSN', models.CharField(blank=True, max_length=20, null=True)),
                ('volume', models.CharField(blank=True, max_length=20, null=True)),
                ('issue', models.CharField(blank=True, max_length=20, null=True)),
                ('page_numbers', models.CharField(blank=True, max_length=50, null=True)),
                ('month', models.CharField(blank=True, choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=20, null=True)),
                ('year_of_publication', models.PositiveIntegerField(blank=True, null=True)),
                ('indexed_in', models.CharField(blank=True, max_length=255, null=True)),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('DOI_or_URL', models.URLField(blank=True, null=True)),
                ('funding_acknowledgement', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'Not Applicable'), ('other', 'Other')], default='no', max_length=20)),
                ('Num_of_authors_from_iilm', models.PositiveIntegerField(default=0, help_text='Number of authors from IILM University')),
            ],
        ),
    ]
