# Generated by Django 5.2.4 on 2025-08-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_journalpublication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_paper', models.CharField(max_length=255)),
                ('author_position', models.CharField(choices=[('first', 'First Author'), ('second', 'Second Author'), ('third', 'Third Author'), ('fourth', 'Fourth Author'), ('fifth', 'Fifth Author'), ('sixth', 'Sixth Author'), ('corresponding', 'Corresponding Author'), ('other', 'Other Author')], default='first', max_length=20)),
                ('corresponding_author', models.CharField(blank=True, max_length=100, null=True)),
                ('conference_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organizing_body', models.CharField(blank=True, max_length=255, null=True)),
                ('ISBN', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(choices=[('national', 'National'), ('international', 'International'), ('other', 'Other')], default='national', max_length=20)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_conference', models.DateField(blank=True, null=True)),
                ('DOI_or_URL', models.URLField(blank=True, null=True)),
                ('indexed_in', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_took_from_iilm', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'Not Applicable'), ('other', 'Other')], default='no', max_length=20)),
                ('Num_of_authors_from_iilm', models.PositiveIntegerField(default=0, help_text='Number of authors from IILM University')),
            ],
        ),
    ]
