# Generated by Django 5.2.4 on 2025-08-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conferencepublication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_agency', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_investigator', models.CharField(choices=[('principal', 'Principal Investigator'), ('co_investigator', 'Co-Investigator'), ('other', 'Other')], default='principal', max_length=20)),
                ('amount_sanctioned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_from', models.DateField(blank=True, null=True)),
                ('duration_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('halted', 'Halted'), ('submitted', 'Submitted')], default='ongoing', max_length=20)),
                ('outcome', models.CharField(choices=[('publication', 'Publication'), ('patent', 'Patent'), ('product', 'Product'), ('other', 'Other')], default='publication', max_length=20)),
                ('num_of_authors_from_iilm', models.PositiveIntegerField(default=0, help_text='Number of authors from IILM University')),
            ],
        ),
    ]
