# Generated by Django 5.2.4 on 2025-08-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_researchprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_patent', models.CharField(blank=True, max_length=255, null=True)),
                ('investors', models.CharField(blank=True, help_text='Comma-separated list of investors', max_length=255, null=True)),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('granted', 'Granted'), ('rejected', 'Rejected'), ('other', 'Other')], default='filed', max_length=20)),
                ('patent_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_published', models.DateField(blank=True, null=True)),
                ('date_of_granted', models.DateField(blank=True, null=True)),
                ('jurisdiction', models.CharField(choices=[('national', 'National'), ('international', 'International'), ('other', 'Other')], default='national', max_length=20)),
                ('type', models.CharField(choices=[('utility', 'Utility'), ('design', 'Design'), ('plant', 'Plant'), ('provisional', 'Provisional'), ('non_provisional', 'Non-Provisional'), ('other', 'Other')], default='utility', max_length=20)),
                ('num_of_authors_from_iilm', models.PositiveIntegerField(default=0, help_text='Number of authors from IILM University')),
            ],
        ),
    ]
