# Generated by Django 5.2.4 on 2025-08-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_patents'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_work', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('software', 'Software'), ('other', 'Other'), ('manual', 'Manual'), ('course_material', 'Course Material')], default='book', max_length=20)),
                ('authors', models.CharField(blank=True, help_text='Comma-separated list of authors', max_length=255, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_grant', models.DateField(blank=True, null=True)),
                ('numbers_of_authors_from_iilm', models.PositiveIntegerField(default=0, help_text='Number of authors from IILM University')),
            ],
        ),
    ]
