# Generated by Django 5.2.4 on 2025-08-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_copyrights'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhdGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_scholar', models.CharField(blank=True, max_length=255, null=True)),
                ('outside_iilm', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'Not Applicable'), ('other', 'Other')], default='no', max_length=20)),
                ('thesis_title', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('supervisor', 'Supervisor'), ('co_supervisor', 'Co-Supervisor'), ('committee_member', 'Committee Member'), ('other', 'Other')], default='supervisor', max_length=20)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('halted', 'Halted'), ('submitted', 'Submitted')], default='ongoing', max_length=20)),
                ('date_of_completion', models.DateField(blank=True, help_text='Date of completion (if applicable)', null=True)),
                ('other_superviser_or_co_superviser', models.CharField(blank=True, help_text='Name of other supervisor or co-supervisor of IILM (if applicable)', max_length=255, null=True)),
            ],
        ),
    ]
