# Generated by Django 5.2.4 on 2025-08-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_phdguidance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chap_title', models.CharField(blank=True, max_length=255, null=True)),
                ('book_title', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('ISBN', models.CharField(blank=True, max_length=20, null=True)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('indexed_in', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'Not Applicable'), ('other', 'Other')], default='no', max_length=20)),
                ('author_position', models.CharField(choices=[('first', 'First Author'), ('second', 'Second Author'), ('third', 'Third Author'), ('fourth', 'Fourth Author'), ('fifth', 'Fifth Author'), ('sixth', 'Sixth Author'), ('corresponding', 'Corresponding Author'), ('other', 'Other Author')], default='first', max_length=20)),
                ('corresponding_author', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_authors_from_iilm', models.PositiveIntegerField(default=0, help_text='Number of authors from IILM University')),
            ],
        ),
    ]
