# Generated by Django 5.2.4 on 2025-08-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bookchapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_book', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('authored', 'Authored'), ('edited', 'Edited'), ('other', 'Other')], default='authored', max_length=20)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('ISBN', models.CharField(blank=True, max_length=20, null=True)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('indexed_in', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'Not Applicable'), ('other', 'Other')], default='no', max_length=20)),
                ('authors_or_editors', models.CharField(blank=True, help_text='Comma-separated list of authors or editors', max_length=255, null=True)),
                ('num_of_authors_from_iilm', models.PositiveIntegerField(default=0, help_text='Number of authors or editors from IILM University')),
            ],
        ),
    ]
