# Generated by Django 5.2.4 on 2025-08-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_partner', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, help_text='Duration of the project (e.g., 6 months, January 2025 - June 2025)', max_length=100, null=True)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount received for the project', max_digits=10, null=True)),
                ('role', models.CharField(blank=True, help_text='Your role in the project (e.g., Lead Consultant, Co-Consultant)', max_length=100, null=True)),
                ('outcome', models.TextField(blank=True, help_text='Outcome of the project', null=True)),
                ('MoU_signed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'Not Applicable'), ('other', 'Other')], default='no', help_text='Is there a Memorandum of Understanding (MoU) signed for this project?', max_length=20)),
                ('num_of_other_project_members_from_iilm', models.PositiveIntegerField(default=0, help_text='Number of other project members from IILM University')),
            ],
        ),
    ]
