# Generated by Django 5.2.4 on 2025-08-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_consultancyprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('editor_role', models.CharField(choices=[('editor_in_chief', 'Editor-in-Chief'), ('associate_editor', 'Associate Editor'), ('section_editor', 'Section Editor'), ('editor', 'Editor'), ('guest_editor', 'Guest Editor'), ('reviewer', 'Reviewer'), ('other', 'Other')], default='editor', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
