# Generated by Django 5.2.4 on 2025-08-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_editorialroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(blank=True, help_text='Name of the journal or conference', max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, help_text='Publisher of the journal or conference proceedings', max_length=255, null=True)),
                ('freq_of_review', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('annually', 'Annually'), ('as_needed', 'As Needed'), ('other', 'Other')], default='as_needed', max_length=20)),
                ('indexing', models.CharField(choices=[('scopus', 'Scopus'), ('web_of_science', 'Web of Science'), ('google_scholar', 'Google Scholar'), ('SCI', 'SCI'), ('other', 'Other'), ('not_indexed', 'Not Indexed')], default='not_indexed', max_length=20)),
            ],
        ),
    ]
