# Generated by Django 5.2.4 on 2025-08-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reviewerroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_award', models.CharField(blank=True, max_length=255, null=True)),
                ('awarding_body', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('national', 'National'), ('international', 'International'), ('university', 'University'), ('departmental', 'Departmental'), ('other', 'Other')], default='university', max_length=20)),
                ('date_of_award', models.DateField(blank=True, null=True)),
                ('nature_of_contribution', models.TextField(blank=True, help_text='Nature of your contribution to the award', null=True)),
            ],
        ),
    ]
