# Generated by Django 5.2.4 on 2025-08-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nature_of_collaborations', models.TextField(blank=True, help_text='Nature of collaborations with the industry (e.g., joint research, consultancy, training)', null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('outcomes', models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('consultancy', 'Consultancy'), ('training', 'Training'), ('other', 'Other')], default='research', max_length=20)),
                ('mou_signed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'Not Applicable'), ('other', 'Other')], default='no', help_text='Is there a Memorandum of Understanding (MoU) signed for this collaboration?', max_length=20)),
            ],
        ),
    ]
