# Generated by Django 5.2.4 on 2025-08-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_industrycollaboration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_taught', models.TextField(blank=True, help_text='List the courses you have taught during the reporting period.', null=True)),
                ('teaching_innovations', models.TextField(blank=True, help_text='Describe any innovative teaching methods or practices you have implemented.', null=True)),
                ('student_mentoring', models.TextField(blank=True, help_text='Detail your student mentoring activities, including any notable achievements.', null=True)),
                ('publications', models.TextField(blank=True, help_text='List any publications you have authored or co-authored during the reporting period.', null=True)),
                ('research_projects', models.TextField(blank=True, help_text='Describe any research projects you have been involved in.', null=True)),
                ('conference_presentations', models.TextField(blank=True, help_text='List any conference presentations you have made during the reporting period.', null=True)),
                ('instituional_services', models.TextField(blank=True, help_text='Detail your contributions to institutional services, such as committees or administrative roles.', null=True)),
                ('professional_services', models.TextField(blank=True, help_text='Detail your contributions to professional services, such as editorial roles, conference organization, or community engagement.', null=True)),
                ('community_services', models.TextField(blank=True, help_text='Detail your contributions to community services, such as outreach programs or social initiatives.', null=True)),
                ('professional_development', models.TextField(blank=True, help_text='Describe any professional development activities you have undertaken, such as workshops or training.', null=True)),
                ('major_achievements', models.TextField(blank=True, help_text='Highlight any major achievements or milestones reached during the reporting period.', null=True)),
                ('goals_for_next_year', models.TextField(blank=True, help_text='Set your goals for the next academic year, including any specific targets or areas of focus.', null=True)),
                ('required_resources', models.TextField(blank=True, help_text='List any resources required to achieve your goals for the next academic year.', null=True)),
                ('current_CV', models.FileField(blank=True, help_text='Upload your current CV.', null=True, upload_to='faculty_reports/cvs/')),
                ('Additional_documents', models.FileField(blank=True, help_text='Upload any additional documents relevant to your report.', null=True, upload_to='faculty_reports/additional_docs/')),
                ('checkbox_agreement', models.BooleanField(default=False, help_text='I confirm that the information provided in this report is accurate and complete.')),
                ('additional_comments', models.TextField(blank=True, help_text='Provide any additional comments or information you would like to include in your report.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='draft', max_length=20)),
            ],
        ),
    ]
