# Generated by Django 5.2.4 on 2025-08-05 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_facultyreport_submissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissions',
            options={'ordering': ['-submission_date']},
        ),
        migrations.AddField(
            model_name='submissions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
