# Generated by Django 5.2.4 on 2025-08-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_submissions_options_submissions_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyReport',
        ),
        migrations.DeleteModel(
            name='Submissions',
        ),
    ]
