# Generated by Django 5.2.4 on 2025-08-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_awards_user_book_user_bookchapter_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualFacultyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_taught', models.TextField(blank=True, help_text='List of courses taught in the academic year', null=True)),
                ('teaching_innovations', models.TextField(blank=True, help_text='Description of teaching innovations implemented', null=True)),
                ('student_mentoring', models.TextField(blank=True, help_text='Description of student mentoring activities', null=True)),
                ('publications', models.TextField(blank=True, help_text='List of publications in the academic year', null=True)),
                ('research_projects', models.TextField(blank=True, help_text='Description of research projects undertaken', null=True)),
                ('conference_presentations', models.TextField(blank=True, help_text='Description of conference presentations made', null=True)),
                ('institutional_service', models.TextField(blank=True, help_text='Description of institutional service activities', null=True)),
                ('professional_service', models.TextField(blank=True, help_text='Description of professional service activities', null=True)),
                ('community_service', models.TextField(blank=True, help_text='Description of community service activities', null=True)),
                ('professional_development', models.TextField(blank=True, help_text='Description of professional development activities', null=True)),
                ('major_achievements', models.TextField(blank=True, help_text='Description of major achievements in the academic year', null=True)),
                ('goals', models.TextField(blank=True, help_text='Description of goals for the upcoming academic year', null=True)),
                ('required_resources', models.TextField(blank=True, help_text='Description of resources required to achieve the goals', null=True)),
                ('current_cv', models.FileField(blank=True, help_text='Upload your current CV', null=True, upload_to='cv/')),
                ('additional_documents', models.FileField(blank=True, help_text='Upload any additional documents', null=True, upload_to='cv/')),
                ('check_box', models.BooleanField(default=False, help_text='I confirm that the information provided is accurate and complete.')),
                ('additional_comments', models.TextField(blank=True, help_text='Any additional comments or information.', null=True)),
            ],
        ),
    ]
