# Generated by Django 5.2.4 on 2025-08-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_annualfacultyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_research_proposal', models.CharField(blank=True, help_text='Enter the title of the research proposal', max_length=255, null=True)),
                ('abstract', models.TextField(blank=True, help_text='Provide a brief abstract of the research proposal', null=True)),
                ('objectives', models.TextField(blank=True, help_text='List the objectives of the research proposal', null=True)),
                ('research_methodology', models.TextField(blank=True, help_text='Describe the research methodology to be used', null=True)),
                ('expected_outcomes', models.TextField(blank=True, help_text='List the expected outcomes of the research proposal', null=True)),
                ('budget', models.TextField(blank=True, help_text='Provide a detailed budget for the research proposal', null=True)),
                ('budget_breakdown', models.TextField(blank=True, help_text='Provide a breakdown of the budget for the research proposal', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Enter the start date of the research project', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Enter the end date of the research project', null=True)),
                ('detailed_proposal', models.FileField(blank=True, help_text='Upload the detailed research proposal document', null=True, upload_to='research_proposals/')),
                ('supporting_documents', models.FileField(blank=True, help_text='Upload any supporting documents for the research proposal', null=True, upload_to='research_proposals/')),
                ('declaration', models.BooleanField(default=False, help_text='I confirm that the information provided is accurate and complete.')),
                ('signature_img', models.ImageField(blank=True, help_text='Upload your signature image', null=True, upload_to='research_proposals/signatures/')),
            ],
        ),
    ]
