# Generated by Django 5.2.4 on 2025-08-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_researchgrantapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceTravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_conference', models.CharField(blank=True, help_text='Enter the title of the conference', max_length=255, null=True)),
                ('conference_website', models.URLField(blank=True, help_text='Enter the conference website URL', null=True)),
                ('organizers_name_affiliation', models.CharField(blank=True, help_text='Enter the name and affiliation of the conference organizer', max_length=255, null=True)),
                ('conference_venue', models.CharField(blank=True, help_text='Enter the venue of the conference', max_length=255, null=True)),
                ('from_date', models.DateField(blank=True, help_text='Enter the start date of the conference', null=True)),
                ('to_date', models.DateField(blank=True, help_text='Enter the end date of the conference', null=True)),
                ('type_of_participation', models.CharField(blank=True, help_text='Enter the type of participation (e.g., presenter, attendee)', max_length=255, null=True)),
                ('title_of_research_paper', models.CharField(blank=True, help_text='Enter the title of the research paper', max_length=255, null=True)),
                ('abstract', models.TextField(blank=True, help_text='Provide a brief abstract of the research paper', null=True)),
                ('acceptance_letter', models.FileField(blank=True, help_text='Upload the acceptance letter for the conference', null=True, upload_to='conference_papers/acceptance_letters/')),
                ('travel_choice', models.CharField(blank=True, help_text='Enter your travel choice (e.g., flight, train, etc.)', max_length=255, null=True)),
                ('travel_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Enter your estimated travel budget', max_digits=10, null=True)),
                ('accommodation_details', models.TextField(blank=True, help_text='Provide details about your accommodation arrangements', null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the total amount for the conference', max_digits=10, null=True)),
                ('prev_fund_checkbox', models.BooleanField(default=False, help_text='I confirm that I have not received any previous funding for this or any conference.')),
                ('justification', models.TextField(blank=True, help_text='Provide a justification for attending the conference', null=True)),
                ('attachments', models.FileField(blank=True, help_text='Upload any additional attachments for the conference', null=True, upload_to='conference_papers/attachments/')),
                ('dean_approval', models.BooleanField(default=False, help_text='I confirm that I have obtained the necessary approvals for this conference attendance.')),
            ],
        ),
    ]
