# Generated by Django 5.2.4 on 2025-08-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_conferencetravelrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_publication', models.CharField(blank=True, help_text='Enter the title of the publication', max_length=255, null=True)),
                ('authors', models.CharField(blank=True, help_text='Enter the authors of the publication', max_length=255, null=True)),
                ('type_of_publication', models.CharField(blank=True, help_text='Enter the type of publication (e.g., journal article, conference paper)', max_length=255, null=True)),
                ('publisher_name', models.CharField(blank=True, help_text='Enter the name of the publisher', max_length=255, null=True)),
                ('year_of_publication', models.PositiveIntegerField(blank=True, help_text='Enter the year of publication', null=True)),
                ('doi', models.CharField(blank=True, help_text='Enter the DOI (Digital Object Identifier) of the publication', max_length=255, null=True)),
                ('abstract', models.TextField(blank=True, help_text='Enter the abstract of the publication', null=True)),
                ('categories', models.CharField(blank=True, help_text='Enter the categories of the publication (e.g., research, review)', max_length=255, null=True)),
                ('checkbox', models.BooleanField(default=False, help_text='I confirm that the information provided is accurate and complete.')),
            ],
        ),
    ]
