# Generated by Django 5.2.4 on 2025-08-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_publicationsupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.CharField(blank=True, help_text='Enter the title of the program', max_length=255, null=True)),
                ('program_description', models.TextField(blank=True, help_text='Enter a description of the program', null=True)),
                ('program_goals', models.TextField(blank=True, help_text='Enter the goals of the program', null=True)),
                ('program_outcomes', models.TextField(blank=True, help_text='Enter the expected outcomes of the program', null=True)),
                ('program_implementation_plan', models.TextField(blank=True, help_text='Enter the implementation plan for the program', null=True)),
                ('program_duration', models.CharField(blank=True, help_text='Enter the duration of the program', max_length=255, null=True)),
                ('program_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the budget for the program', max_digits=10, null=True)),
                ('program_justification', models.TextField(blank=True, help_text='Enter a justification for the program', null=True)),
                ('program_attachments', models.FileField(blank=True, help_text='Upload any additional attachments for the program', null=True, upload_to='curriculum_development/attachments/')),
                ('dean_approval', models.BooleanField(default=False, help_text='I confirm that I have obtained the necessary approvals for this program.')),
            ],
        ),
    ]
