# Generated by Django 5.2.3 on 2025-08-22 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('cluster_head', 'Cluster Head'), ('dean', 'Dean'), ('admin', 'Admin')], default='faculty', max_length=20),
        ),
        migrations.CreateModel(
            name='FacultySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('journal_publication', 'Journal Publication'), ('conference_publication', 'Conference Publication'), ('research_projects', 'Research Projects'), ('patents', 'Patents'), ('copyrights', 'Copyrights'), ('phd_guidance', 'PhD Guidance'), ('book_chapter', 'Book Chapter'), ('book', 'Book'), ('consultancy_projects', 'Consultancy Projects'), ('editorial_roles', 'Editorial Roles'), ('reviewer_roles', 'Reviewer Roles'), ('awards', 'Awards'), ('industry_collaboration', 'Industry Collaboration'), ('annual_faculty_report', 'Annual Faculty Report'), ('research_grant_application', 'Research Grant Application'), ('conference_travel_request', 'Conference Travel Request'), ('publications_update', 'Publications Update'), ('curriculum_development', 'Curriculum Development')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.JSONField(default=dict, help_text='Stores the actual submission data')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facultysubmission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested'), ('resubmitted', 'Resubmitted')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='core.facultysubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='facultysubmission',
            index=models.Index(fields=['status', 'submission_type'], name='core_facult_status_5637f1_idx'),
        ),
        migrations.AddIndex(
            model_name='facultysubmission',
            index=models.Index(fields=['user', 'status'], name='core_facult_user_id_a04ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='facultysubmission',
            index=models.Index(fields=['department', 'status'], name='core_facult_departm_d53aa1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewerassignment',
            unique_together={('submission', 'reviewer')},
        ),
    ]
